language: node_js
before_script:
  - npm install -g gulp
script: gulp
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: AKIAISC4OB2CVWUR7WYQ
  secret_access_key:
    secure: Qv5VfelbGByiblzfpxezThPGvFQIfgvXmTnp1tLfKeQ4DEs97Olg2p+7yXxcHpqm64IoyCTbyi+EHgH99ryqoqUyv0i5dmfsGcpktrYn/VD/faZzWoVdGDjy2sog4AOcI+LWHf7ZKSbtqaM/kmfBzonvdOPhtHv/CtgtiiMTOCLKgr5hZnoBA2K2iNys0wO9soOJfjkMAEOuhXuy5igfNZcPjnXoWizPJToiom4HZRiM14aajUaDYFJ3dDIfhGX1ChTT6iYqDSbm3Tg410aMTlDX9TqEZ4wVwdxJnzmcEET1SqyYk3x3SEtjHXZXZH4VvFKkMlTzu3GSB5l1XToBRo/tUvGlyGymQb+hJFtucC36XnNRznNyi2fbXCOdu/M0N6uDPEOgx2xMO4ByWe17Bx9naqrZmlPw+lxRSHqMvX5u+SGbJjJ3c2pN/oW0j+XK+vml49QkX4ZhMcOE9BO/DOZwBEkw2xZOQc1uFBtQ1sNMo6Cioj6QZCzlfBhGcAC3apfYIAHkJj31gi1ZfvRrvpC7NoEBwfW8bmqKdt1v691xKtLppv8AhBD1rRN7sWlbsnX7COWoyxUiciyW1xRT88+7iPtA3BnME9IZ65S7Q73TFIbs6zQfDowGlK+ifOCaaQVtcmUfkRL2nWtfFUoWIk1eipYeuWrY2JtcQpwXKAQ=
  bucket: equitableaid.ctdata.org
  acl: public_read
  on:
    repo: CT-Data-Collaborative/equitable-aid
    branch: master